AWSTemplateFormatVersion: 2010-09-09
Description: Creates persistent storage for AWS security essentials

Parameters:
  CloudtrailBucketName:
    Description: Name to use for the S3 bucket that stores the cloudtrail logs
    Type: String
  ConfigBucketName:
    Description: Name to use for the S3 bucket that stores the config data
    Type: String


Resources:
  ConfigBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy : Retain
    Properties:
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 730
          Status: Enabled
      BucketName:
        Ref: ConfigBucketName

  ConfigBucketPolicy:
    Type : AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ConfigBucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: config.amazonaws.com
          Action: s3:GetBucketAcl
          Resource: !Sub arn:aws:s3:::${ConfigBucketName}
        - Effect: Allow
          Principal:
            Service: config.amazonaws.com
          Action: s3:PutObject
          Resource: !Sub arn:aws:s3:::${ConfigBucketName}/*

  CloudtrailBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy : Retain
    Properties:
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 730
          Status: Enabled
      BucketName:
        Ref: CloudtrailBucketName

  # See http://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-s3-bucket-policy-for-cloudtrail.html
  CloudtrailBucketPolicy:
    Type : AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: CloudtrailBucket
      PolicyDocument:
        Statement:
        - Sid: AWSCloudTrailAclCheck20150319
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action: s3:GetBucketAcl
          Resource:
            Fn::Join:
            - ""
            - - "arn:aws:s3"
              - ":::"
              - Ref: CloudtrailBucketName
        - Sid: AWSCloudTrailWrite20150319
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action: s3:PutObject
          Resource:
            Fn::Join:
            - ""
            - - "arn:aws:s3"
              - ":::"
              - Ref: CloudtrailBucketName
              # more secure to scope to each AWS account individually, but that
              # would be a management overhead, especially with AWS accounts being
              # created fairly regularly. This allows any AWS account to name our
              # bucket as a CloudTrail location (put-only and in their own subdir)
              - /AWSLogs/*
          Condition:
            StringEquals:
              "s3:x-amz-acl": bucket-owner-full-control

